### ISSUE TITLE
Add (nearly) full screen option

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-overlay#143]
KAT would like some really big interstitials where the overlay goes much closer to the edge of the screen.

**Comment by gvonkoss** [comment]
@leggsimon do you still need this?

**Comment by leggsimon** [comment]
Hmm, I'm not sure. I'm not entirely sure I remember what this was for or entirely what Alice's comment means.  Does it mean instead of 
![screenshot 2018-01-15 12 01 23](https://user-images.githubusercontent.com/11544418/34941565-2d5bb15a-f9ec-11e7-90f7-67c407cfa2d7.png)

We could have 
![screenshot 2018-01-15 12 02 59](https://user-images.githubusercontent.com/11544418/34941570-328b073e-f9ec-11e7-921c-8c21474722b4.png)


?

**Comment by gvonkoss** [comment]
I'm not familiar with what you use o-overlay for (if not the example above), but if you don't need it I would be inclined to close the issue?

**Comment by leggsimon** [comment]
🤷‍♂️ 🤷‍♀️ No one seems to know!

**Comment by samuele-artuso** [comment]
Reopening as I need a full screen overlay.

I'm working on this:

![image](https://user-images.githubusercontent.com/3853889/35692909-7a00ed3c-0774-11e8-9fb7-23578898327a.png)

**Comment by samuele-artuso** [comment]
@luketudorgriffiths

**Comment by notlee** [comment]
https://github.com/Financial-Times/o-overlay/releases/tag/v2.2.0
