### ISSUE TITLE
O-overlay wrapper is 'undefined' first time when the overlay is opened

### ISSUE THREAD

**Issue by cristinanegoescu** [Financial-Times/o-overlay#33]
Hello,

I'm trying to insert the o-overlay component for ft.com and I have some problems.

Here is the code I'm using:

```js
var wrapper = bundles['o-overlay'].getOverlays()['wideSquat'].wrapper;
var wrapper_el = FT.$(wrapper);
console.log('wrapper: ',wrapper);
console.log('wrapper_el length: ', wrapper_el.length);
wrapper_el.ready(function(){
    console.log('wrapper open');
});
```

When the page is loading and I click on the button to open the overlay, I get 'undefined' value for wrapper and wrapper_el.length is 0. And if I close it and open again, the wrapper is ok and also I get wrapper_el.length = 1. Why is not working first time and why is working after that?

I also tried to use: var myOverlay = new bundles'o-overlay'; but I need to set the 'data-o-overlay-arrow-position' attribute and I didn't find a way for that. But this is another problem.

Please let me know if you can help me with the firt one.

Thanks

**Comment by AlbertoElias** [comment]
So what's happening here is that the trigger isn't instantiated until the build service emits the o.DOMContentLoaded event, and that happens when the page has loaded. I spoke with @cristinanegoescu and explained how she could instantiate the module manually but adding the autoinit=0 in the build service url and running bundle['o-overlay'].init().

About the second issue, you can set config options when instantiating the module imperatively like this:

```js
var myOverlay = new Overlay('myOverlay', {
    html: 'Hello world',
    trigger: '.blah',
    arrow: {
        position: 'bottom'
    }
});
```
It's explained [here](https://github.com/Financial-Times/o-overlay#imperatively)

**Comment by AlbertoElias** [comment]
@cristinanegoescu Can this be closed?
