### ISSUE TITLE
Issues with position: fixed in iOS

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#41]
http://jsbin.com/borilaregi/1/edit

Open the overlay, note that:
1. it scrolls the page up a bit
2. while the keypad is open, the overlay's position is not fixed (could be iOS issue)
3. Can't scroll to bottom of the overlay.

Note that the overlay has an input box with autofocus.

**Comment by AlbertoElias** [comment]
Position: fixed doesn't work great on iOS, I'll take a look and see if there's a good fix for this

**Comment by Vallach** [comment]
Any updates on these issues? 
Note: iPad related defects should be treated as high priority

**Comment by kaelig** [comment]
Virtual keyboard breaks position fixed in iOS:
- http://stackoverflow.com/questions/14492613/ios-ipad-fixed-position-breaks-when-keyboard-is-opened
- http://stackoverflow.com/questions/25612442/position-fixed-does-not-work-when-the-virtual-keyboard-is-shown-in-ios

The way Bootstrap seem overcome that modal issue in iOS is by simply scrolling to the top of the page when a form is focused and the virtual keyboard displayed in a modal box.

(note: there are almost [1200 issues related to the modal component](https://github.com/twbs/bootstrap/issues?q=is%3Aissue+is%3Aopen+modal+is%3Aclosed) in Bootstrap…)

**Comment by AlbertoElias** [comment]
@kaelig That solution is not that practical though. In the case of o-comments, the module is used in the middle of the page. Scrolling to the top is just as bad as #52 

This is a hard one, I'll check out more examples and if there's not a clear work around, I think we'll have to leave it as is

**Comment by AlbertoElias** [comment]
I'm going to close this and mark it as won't fix. We can't do anything about position: fixed. We've done a few other improvements so that it is usable at least The convention for mobile is to [not even use overlays](http://mobilewebbestpractices.com/user-experience/count-on-modal-windowsoverlays/), we should probably start thinking about this, specially for Next @danskinner

**Comment by roland-vachter** [comment]
Hi Alberto, that's fine. Although the "not even use overlays" not gonna work in my opinion (in most cases), for sure not for comments for example (which will be part of Next as well).

**Comment by AlbertoElias** [comment]
The not use overlays is basically: let's all sit down together and see if we can find a way to do this that provides a better user experience on mobile. No design has to be definite imho
